name: capstone_project
description: "capsA new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  fl_chart: ^0.71.0
  flutter_svg: ^2.0.5
  firebase_core: ^3.13.0
  firebase_database: ^11.0.0
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  async: ^2.8.2
  settings_ui: ^2.0.2
  provider: ^6.1.5
  flutter_carousel_widget: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/test1.png
    - assets/images/test2.png
    - assets/images/test3.jpg
    - assets/images/test4.png
    - assets/images/test5.png
    - assets/icons/  
